[phases.setup]
nixPkgs = ["nodejs-18_x", "python3"]

[phases.install]
cmds = [
  "cd backend && PUPPETEER_SKIP_DOWNLOAD=true npm ci"
]

[phases.build]
cmds = [
  "sudo apt-get update && sudo apt-get install -y --no-install-recommends chromium chromium-browser fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libcups2 libdbus-1-3 libdrm2 libgbm1 libgtk-3-0 libnspr4 libnss3 libx11-xcb1 libxcomposite1 libxdamage1 libxrandr2 xdg-utils"
]

[start]
cmd = "cd backend && npm start"

[variables]
NODE_ENV = "production"