[phases.setup]
nixPkgs = [
  "nodejs-18_x",
  "python3",
  "chromium",
  "nss",
  "atk",
  "gtk3",
  "libxcomposite",
  "libxdamage",
  "libxrandr",
  "libx11",
  "xdg-utils",
  "libdrm",
  "cups",
  "glib"
]

[phases.install]
cmds = [
  "cd backend && PUPPETEER_SKIP_DOWNLOAD=true npm ci"
]

[phases.build]
cmds = [
  "echo 'No apt commands needed. All Puppeteer dependencies are in nixPkgs.'"
]

[start]
cmd = "cd backend && npm start"

[variables]
NODE_ENV = "production"