[phases.setup]
nixPkgs = ["nodejs-18_x", "python3"]

[phases.install]
cmds = [
  "cd backend && PUPPETEER_SKIP_DOWNLOAD=true npm ci"
]

[phases.build]
cmds = [
  "sudo apt-get update && sudo apt-get install -y chromium"
]

[start]
cmd = "cd backend && npm start"

[variables]
NODE_ENV = "production" 