[phases.setup]
nixPkgs = ["nodejs-18_x", "python3"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["echo 'No build step required for this backend'"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production" 